### ISSUE TITLE
Crash using Sacrificial Knife

### ISSUE THREAD

**Issue by SirWilli** [cyanobacterium/DrCyanos_Lootable-Bodies#16]
Versions: 1.7.10 - 1.3.6

```
java.lang.NullPointerException: Unexpected error
	at cyano.lootable.entities.EntityLootableBody.updatePlayerProfile(EntityLootableBody.java:142)
	at cyano.lootable.entities.EntityLootableBody.setOwner(EntityLootableBody.java:118)
	at cyano.lootable.events.PlayerDeathEventHandler.playerDeathEvent(PlayerDeathEventHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_458_PlayerDeathEventHandler_playerDeathEvent_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayer.func_70645_a(EntityPlayer.java:630)
	at WayofTime.alchemicalWizardry.common.items.SacrificialDagger.func_77659_a(SacrificialDagger.java:153)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1964)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cyano.lootable.entities.EntityLootableBody.updatePlayerProfile(EntityLootableBody.java:142)
	at cyano.lootable.entities.EntityLootableBody.setOwner(EntityLootableBody.java:118)
	at cyano.lootable.events.PlayerDeathEventHandler.playerDeathEvent(PlayerDeathEventHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_458_PlayerDeathEventHandler_playerDeathEvent_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayer.func_70645_a(EntityPlayer.java:630)
	at WayofTime.alchemicalWizardry.common.items.SacrificialDagger.func_77659_a(SacrificialDagger.java:153)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
```

**Comment by cyanobacterium** [comment]
Sorry for the delay. Under what conditions do you get this crash?

**Comment by SirWilli** [comment]
What do you mean?
Just use the knife until you die with blood magic and lootable bodies installed and it will crash.

**Comment by cyanobacterium** [comment]
I see. You didn't mention the killing yourself with the knife in this post, but I see it started as an issue on a different mod page. 

It looks like something about how the knife kills you messes with Minecraft's ability to figure out the game profile of the suicidal player. I'm not doing any further development on Minecraft 1.7, but I'll throw a try-catch in there to keep it from crashing (other bugs may persist).

**Comment by cyanobacterium** [comment]
Here's my fix:
https://github.com/cyanobacterium/DrCyanos_Lootable-Bodies/releases/download/1.3.6-backport/CyanosLootableBodies-1.7.10-backport_1.3.7.jar
That'll stop the crashes. I don't know if it'll fix the duplication bug, but if not, I'm not planning any more bugs fixes for the backport unless the bugs are really severe.

**Comment by SirWilli** [comment]
Thanks, only issue is now that it spawns the bodies twice:

![](https://i.imgur.com/V1sDtMi.png)

but the second one is gone after relog and you can't take the items.
